### PR TITLE
remove optional signup request fields

### PR DESCRIPTION
**Pull request by sabrimete**
PR for the issue https://github.com/bounswe/bounswe2022group7/issues/391

### CODE REVIEW

**Comment by demet47** [comment]
It all works fine on my local. I reviewed the code also. It is all fine thus I am merging the PR.

**Comment by CahidArda** [comment]
Neither issue #391 nor the PR #396 contains the removed fields. I had to check the commit to see what were removed. Please provide them for our sake. 

Please also provide the postman setup (HTTP Method GET/POST, post body) you used in testing. I couldn't signup with the following setup. I get a bad request error which doesn't help me with debugging.

image

Docker prints the following error:

```
artshare-backend   | 2022-11-13 12:33:08.786  WARN 111 --- [nio-8080-exec-2] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 1364, SQLState: HY000
artshare-backend   | 2022-11-13 12:33:08.787 ERROR 111 --- [nio-8080-exec-2] o.h.engine.jdbc.spi.SqlExceptionHelper   : Field 'user_id' doesn't have a default value
artshare-backend   | 2022-11-13 12:33:08.787  INFO 111 --- [nio-8080-exec-2] o.h.e.j.b.internal.AbstractBatchImpl     : HHH000010: On release of batch it still contained JDBC statements
artshare-backend   | 2022-11-13 12:33:08.796  WARN 111 --- [nio-8080-exec-2] .w.s.m.a.ResponseStatusExceptionResolver : Resolved [org.springframework.web.server.ResponseStatusException: 400 BAD_REQUEST "could not execute statement; nested exception is org.hibernate.exception.GenericJDBCException: could not execute statement"]
```

**Comment by demet47** [comment]
Hi @CahidArda,
The main difference that hits my eye is the endpoint you are calling. I did the request without the prepended "/api/". My request is as follows:
image

Can you try this and give me feedback again?

**Comment by CahidArda** [comment]
Thansk for the update. I was able to fix the issue. The problem wasn't in "/api/" though. Backend is in "/api/" route when we run the app with `docker-compose`.

The problem was trying to generate a token in [dev/backend/combine-generic-and-user-endpoints](https://github.com/bounswe/bounswe2022group7/tree/dev/backend/combine-generic-and-user-endpoints) branch but the changes you have made here are not present in that branch. It worked when I signed up with the old JSON body.

**Comment by demet47** [comment]
Ah I see. I'm glad you soved it ^_^

**Pull request merged**
