### PR TITLE
Json Related Bug Fix

### PR DESCRIPTION
**Pull request by askabderon**
implementation of [issue](https://github.com/bounswe/bounswe2022group7/issues/323)
and also this resolves the [issue](https://github.com/bounswe/bounswe2022group7/issues/344)

Related art item endpoints are tested, screenshots of the outputs are attached below:
Screen Shot 2022-10-30 at 19 54 10
Screen Shot 2022-10-30 at 19 54 18

### CODE REVIEW

**Comment by demet47** [comment]
It works on my local without error. I read the code as well, nothing peculiar. But there seems some errors related to frontend integration since CI/CD is giving errors so I am transferring the closure of the issue to @CahidArda . (I read the error messages and I don't think they are backend related.)

**Review by CahidArda — APPROVED** [review]
It looks like the errors are fixed in the backend. Thanks a lot for the work.

The CI error is not caused by changes in this PR. I suggest we merge this PR so that other team members won't face the same issue. We can fix the CI issues in another PR.

**Comment by CahidArda** [comment]
We can merge the branch if you approve the PR @demet47.

**Comment by demet47** [comment]
I am merging the PR then @CahidArda thanks for the feedback!

**Pull request merged**
