### PR TITLE
Dev/android/comment vote

### PR DESCRIPTION
**Pull request by AlicanM**
I implemented the comment upvote and downvote feature to the mobile app, details are in [issue](https://github.com/bounswe/bounswe2022group7/issues/568)

### CODE REVIEW

**Review by musasimsekdotdll — CHANGES_REQUESTED** [review]
It seems like backend integration is not completed yet.

After I upvoted/downvoted some comments, page looks like:
Screenshot_2022-12-24-00-36-44-640_com group7 artshare android

However, if I tried to go back and select the same event again:
Screenshot_2022-12-24-00-36-54-604_com group7 artshare android

The page does not show my previous upvotes, downvotes.

**Comment by AlicanM** [comment]
Fixed some bugs and now backend is completed.  It should show your previous upvotes, downvotes.

**Review by AlicanM — COMMENTED** [review]
Fixed some bugs and now backend is completed. It should show your previous upvotes, downvotes.

**Comment by canatakan** [comment]
Hello @AlicanM, for your information, after some updates in `develop`, it is now required for you to resolve the conflicts.

**Review by musasimsekdotdll — APPROVED** [review]

**Comment by musasimsekdotdll** [comment]
Everything seems good after the last updates, I am merging now. Thanks for your great effort.

**Pull request merged**
