### PR TITLE
Dev/backend/vote comment

### PR DESCRIPTION
**Pull request by sabrimete**
PR for the issue: https://github.com/bounswe/bounswe2022group7/issues/534

It takes two input: id and vote. id is comment id and vote is either 1 or -1 meaning upvote and downvote.
Adding members from each front and mobile teams to let them know: @CahidArda @atillaturkmen 

Here are the screenshots of example enpdpoint calls: 
Screenshot 2022-12-08 at 21 45 55
Screenshot 2022-12-08 at 21 46 15
Screenshot 2022-12-08 at 21 46 36
Screenshot 2022-12-08 at 21 46 53

### CODE REVIEW

**Comment by askabderon** [comment]
This is not implemented in this PR but in the fields of Comment, upvoter_user_id and comment_id are reversed. Hence we are storing them in the database with the wrong ids. Other than this, everything seemed fine to me. I run the new endpoints and checked the database. 

I am talking about the 33-34 and 42-43 lines of Comment.kt

**Review by askabderon — CHANGES_REQUESTED** [review]
Please update the Comment.kt file

**Comment by sabrimete** [comment]
> This is not implemented in this PR but in the fields of Comment, upvoter_user_id and comment_id are reversed. Hence we are storing them in the database with the wrong ids. Other than this, everything seemed fine to me. I run the new endpoints and checked the database.
> 
> I am talking about the 33-34 and 42-43 lines of Comment.kt

Yes, you are right. I will fix it in a moment.

**Comment by askabderon** [comment]
LGTM, merging this PR and closing this corresponding issue. Thanks for working on this and creating a PR with detailed explanation @sabrimete!

**Pull request merged**
