### PR TITLE
string to list feature

### LINKED ISSUE #450: Converter from String of List to List
We are currently holding a few fields that are originally lists as their string version to reduce redundant database tables. Frontend is translating this string to list. We are to provide a list and remove their conversion code.

**Deadline:** 30/11/2022 23.59
**Reviewer:** @sabrimete

### PR DESCRIPTION
**Pull request by demet47**
Closes #450.

### CODE REVIEW

**Comment by demet47** [comment]
An example response body is as follows:
image

The change can be observed form category and labels fields. The data for them is stored as string representations.
@CahidArda @canatakan please let me know if I missed any fields for the conversion. I implemented it to labels and categories.

**Comment by askabderon** [comment]
I checked the corresponding endpoints, they run without an error. If there are no more fields that should be updated we can merge the PR @canatakan @CahidArda

**Review by askabderon — APPROVED** [review]

**Review by canatakan — APPROVED** [review]
These changes look good to me, I approve the updates.

**Review by CahidArda — APPROVED** [review]
LGTM!

**Pull request merged**
