### PR TITLE
create art item owner bug fix

### PR DESCRIPTION
**Pull request by demet47**
image
The response body for the above request is as follows:

```
{
    "name": "Hello World!",
    "description": "Call from an ET",
    "category": null,
    "imageId": null,
    "labels": [],
    "creatorAccountInfo": {
        "email": "email_2",
        "username": "username_2",
        "id": 2,
        "name": null,
        "surname": null,
        "country": null,
        "dateOfBirth": null,
        "profilePictureId": null
    },
    "creatorId": 1,
    "creationDate": "2022-11-28T10:27:34.274+00:00",
    "ownerAccountInfo": {
        "email": "email_2",
        "username": "username_2",
        "id": 2,
        "name": null,
        "surname": null,
        "country": null,
        "dateOfBirth": null,
        "profilePictureId": null
    },
    "ownerId": 1,
    "onAuction": false,
    "auction": null,
    "lastPrice": 2.0,
    "commentList": [],
    "bookMarkedByIds": []
}
```

### CODE REVIEW

**Comment by demet47** [comment]
Closes #468.

**Comment by CahidArda** [comment]
The response to the POST request looks good but we need the response of the GET to be updated. Does this PR also add owner information to the GET response?

**Comment by askabderon** [comment]
> The response to the POST request looks good but we need the response of the GET to be updated. Does this PR also add owner information to the GET response?

Yes, GET responses have already updated.

**Comment by askabderon** [comment]
@demet47 we should also add the ArtItemId to the DTO

**Review by askabderon — CHANGES_REQUESTED** [review]
You should update the ArtItemDTO with ArtItem id. And also you should update the homepage controller part that returns all the ArtItems.

**Comment by askabderon** [comment]
Please removed the bookmarkedBy field from ArtItemDTO as well. This field is not related to the public information of Art Item.

**Comment by demet47** [comment]
> You should update the ArtItemDTO with ArtItem id. And also you should update the homepage controller part that returns all the ArtItems.

Done

**Comment by demet47** [comment]
> Please removed the bookmarkedBy field from ArtItemDTO as well. This field is not related to the public information of Art Item.

Done

**Comment by demet47** [comment]
> Reference in

Done

**Review by askabderon — APPROVED** [review]
LGTM, thanks for working on this @demet47!

**Pull request merged**
