### PR TITLE
Dev/backend/combine generic and user endpoints

### PR DESCRIPTION
**Pull request by sabrimete**
PR for this issue: https://github.com/bounswe/bounswe2022group7/issues/393

I combined the endpoints that are for generic and specific user. Right now, if request have a valid user token, it returns for that specific user. If request doesn't have token, then it returns generic results.

I also changed the endpoints paths as follows:

To get the events:
/homepage/event

To get the art items:
/homepage/artItem

### CODE REVIEW

**Comment by sabrimete** [comment]
I'm adding two people as reviewers from frontend and mobile teams.
@CahidArda @atillaturkmen 

Please update your code to send requests to these updated endpoints. If you see any problem, please let me know.

**Review by atillaturkmen — APPROVED** [review]

**Comment by CahidArda** [comment]
I was able to test the endpoint without a token and it works. I wasn't able to test it with a token however. I don't know if @atillaturkmen has tested with a token but I am unable to get a token, because I can't signup. I have provided [the details](https://github.com/bounswe/bounswe2022group7/pull/396#issuecomment-1312720726) in #396.

**Review by CahidArda — APPROVED** [review]
I have tested the endpoints. In the event endpoint it returned a single event without token, no event with a token. In the art item endpoint I received the same thing but I assume it is working correctly.

Also please provide the Postman setups you used for testing next time. I didn't know that this branch was opened before #396 was merged and I tried to create a token with the new API which didn't work. I probably lost half an hour figuring out what was wrong.

Another reason why we desperately need Swagger.

**Comment by CahidArda** [comment]
It looks like everyone approved the PR, shall we merge it?

**Comment by askabderon** [comment]
Merged this PR since every reviewer approve the changes.

**Pull request merged**
