### PR TITLE
Dev/android/profile page finalver

### PR DESCRIPTION
**Pull request by musasimsekdotdll**
As I explained in the [corresponding issue](https://github.com/bounswe/bounswe2022group7/issues/446):

- I fixed the dropdown button(see [an old comment](https://github.com/bounswe/bounswe2022group7/issues/262#issuecomment-1287802753))
- the page is the profile page of an actual user
- the items listed according to the dropdown selection are also actually created by the owner of the profile page, not mock data anymore
- profile customization progress bar is revised

### CODE REVIEW

**Comment by musasimsekdotdll** [comment]
## Dropdown Button

```
class DropdownButtonExample extends StatefulWidget {
  const DropdownButtonExample({super.key});

  @override
  State<DropdownButtonExample> createState() => _DropdownButtonExampleState();
}

class _DropdownButtonExampleState extends State<DropdownButtonExample> {
  String dropdownValue = dropdown_items.first;

  void updateSelectedItems() {
    String selection = dropdown_selection.value;
    if(selection == "Events") {
      selected_items = post_lists[selection]!;
    } else if(selection == "Art Items") {
      selected_items = post_lists[selection]!;
    } else {
      selected_items = ["as"];
    }
  }

  @override
  Widget build(BuildContext context) {
    return DropdownButton<String>(
      isExpanded : true,
      value: dropdownValue,
      icon: const Icon(Icons.keyboard_arrow_down),

      onChanged: (String? value) {
        // This is called when the user selects an item.
        setState(() {
          dropdownValue = value!;
          dropdown_selection.value = value!;
          updateSelectedItems();
        });
      },
      items: dropdown_items.map<DropdownMenuItem<String>>((String value) {
        return DropdownMenuItem<String>(
          value: value,
          child: Text(value, style: Theme.of(context).textTheme.headline6)
        );
      }).toList(),
    );
  }
}
```


I created a widget class inheriting Stateful Widget for dropdown. As you may see, icons of dropdown removed and a global list(_selected_items_) keeping all instances of selected value(events for _Events_, art items for _Art Items_ etc) is updated on every change in the dropdown selection value.


In the actual widget, I just call this _DropdownButtonExample_ widget:
```
Row(
    mainAxisAlignment: MainAxisAlignment.start,
    children: [
        Container(
            decoration: BoxDecoration(
                shape: BoxShape.rectangle,
                border: Border.all(width: 1.85),
                borderRadius: BorderRadius.circular(8.0),
            ),
            height: 35,
            width: 150,
            child: DropdownButtonExample(),
        ),

    ],
),
```

**Comment by musasimsekdotdll** [comment]
## Getting the Actual User from Backend

In order to complete this task; models, networks and other necessary files are created. Here is the list of those files:

- [models/profile/account_info](https://github.com/bounswe/bounswe2022group7/pull/475/files#diff-037a8e1fab135e0e0eb0df3c0b41721c273482a8c3eba9f4004e5bf2a71251cc)
- [models/profile/account_model](https://github.com/bounswe/bounswe2022group7/pull/475/files#diff-b4f61cbc6ce58a3ff3758e954f772bb5ebc7a0cb2fc7adb65ca786b245be4ce2)
- [network/event/get_event_service](https://github.com/bounswe/bounswe2022group7/pull/475/files#diff-647fae1e9e42eab961b0a8171f911c9803d6376fa06cfea8966fda87921edadf)
- [network/profile/get_user_output](https://github.com/bounswe/bounswe2022group7/pull/475/files#diff-9727695bb9c7e1deba4692052ac2f97f14ce922a3b182c3abe1990e40c96026c)
- [network/profile/get_user_service](https://github.com/bounswe/bounswe2022group7/pull/475/files#diff-5fbc7c2dcaadaa1c8f7e1578a218057ead9d7ed06acd090de3b3e514ff7a774d)

**Comment by musasimsekdotdll** [comment]
## Real Item List

After the dropdown button is fixed, it is time to list the corresponding items selected with dropdown button. A value notifier is the key to stay informed about the dropdown selection. Every time the dropdown selection is changed, the widget listing _selected items_ will be updated accordingly.

`var dropdown_selection = ValueNotifier<String>("Events");`

```
 child: ValueListenableBuilder(
    valueListenable: dropdown_selection,
    builder: (context, value, widget) => ListView.builder(
        itemCount: selected_items.length,
        shrinkWrap: true,
        itemBuilder: (BuildContext context, int index) {
            return OutlinedButton(
                onPressed: null,
                child: Column(
                    .
                    .
                    .
```

**Comment by musasimsekdotdll** [comment]
## Profile Customization Progress Bar

The progress bar is now much simple and easy to handle.

```
Container(
    height: 25.0,
    child: LinearPercentIndicator(
        width: MediaQuery.of(context).size.width - 150,
        animation: true,
        lineHeight: 25.0,
        animationDuration: 1200,
        percent: 0.5,
        center: const Text("You completed 1/2 steps of your profile.", style: TextStyle(color: Colors.white, fontSize: 12.0), selectionColor: Colors.white,),
        // linearStrokeCap: LinearStrokeCap.roundAll,
        progressColor: Colors.lightBlue,
        barRadius: Radius.circular(4.0),
        trailing: OutlinedButton(
            onPressed: null,
            child: Row(
                children: [
                    Text("Go complete!", style: TextStyle(color: Colors.blueGrey.shade900),),
                    Icon(Icons.double_arrow_sharp, color: Colors.blueGrey.shade900,),
                ],
            ),
        ),
    ),
)
```

**Review by AlicanM — APPROVED** [review]
I reviewed the changes, there is no problem to report. Thanks for your great effort.

**Pull request merged**
