### PR TITLE
Dev/backend/event item endpoint

### PR DESCRIPTION
**Pull request by demet47**
Changes:
- ArtItem field is removed from ArtItemInfo class since ArtItem won't be reached from ArtItemInfos
- ManyToMany relations' annotations are modified
- with {domainURL}/event/{id} call we can now get an OnlineGallery OR PhysicalEvent with given id. Their id clusters don't overlap and this is provided by connecting these two classes to an abstract class "Event".

### CODE REVIEW

**Comment by sabrimete** [comment]
I changed the base branch from master to backend. Right now there are conflicts you need to solve. I will review the PR again after you solve them.

**Comment by askabderon** [comment]
@demet47 you should not commit the Homepage file since there is no changes. Also, shouldn't we parse labels fields since it is stored as one string?

**Comment by askabderon** [comment]
Moreover, I couldn't understand why we delete ArtItem field from ArtItemInfo. I think we may need the connection later, is there a need to delete it?

**Comment by sabrimete** [comment]
it looks fine, I'm merging it.

**Pull request merged**
