### PR TITLE
[Frontend] Merge revised signup and signing pages to develop

### LINKED ISSUE #338: [Frontend] Revise and connect signup and login to backend
As we have previously implemented the login and signup pages without a backend connection, we need to set up the backend connection. Also we need to achieve feature parity with mobile application, as we don't have some fields they have on their signup page. So I will implement these changes.

**Deadline: 31.10.2021**
**Reviewer: @CahidArda**

### PR DESCRIPTION
**Pull request by erimerkin**
I have updated the functionality of sign up and login pages by adding form validation, backend connection and necessary feedback mechanisms (error alert, information alert, loading icon). All changes are documented in issue #338. Two new packages are added for form validation: **yup**, **formik**.

With merging this branch sign-up and login functionalities of frontend will be completed.

Merging this pull request closes #338.

### CODE REVIEW

**Comment by CahidArda** [comment]
Can we fix the CI related issues in this PR?

**Comment by erimerkin** [comment]
> Can we fix the CI related issues in this PR?
> 
> edit: I am fixing them in my branch.

I have fixed warnings for SignInPage, only Homepage warnings remain

**Comment by CahidArda** [comment]
Why did you delete lines in files in the backend folder?

**Comment by erimerkin** [comment]
> Why did you delete lines in files in the backend folder?

Oh, I merged develop branch to this branch but forgot to commit that merge...

**Review by CahidArda — APPROVED** [review]
Changes look correct to me. I have tested the forms and verification works correctly. Thanks for the work.

**Pull request merged**
