### PR TITLE
Post art item bug fix

### PR DESCRIPTION
**Pull request by askabderon**
This solves the bug on [the issue](https://github.com/bounswe/bounswe2022group7/issues/458)

I checked the creating artItem, creating comment, and getting ArtItem endpoints.
It only adds one comment to the commentList as expected.

```json
{
    "id": 72,
    "artItemInfo": {
        "id": 73,
        "name": "somename",
        "description": "somedesc",
        "category": "[\"kubism\", \"oil painting\", \"wooden sculpture\"]",
        "imageId": null,
        "labels": "[\"romantic\", \"engraving\", \"carving\"]"
    },
    "creationDate": "2022-11-21T15:26:11.000+00:00",
    "owner": null,
    "onAuction": false,
    "auction": null,
    "lastPrice": 5.0,
    "commentList": [
        {
            "id": 104,
            "text": "firstComment",
            "creationDate": "2022-11-26T09:02:12.000+00:00",
            "lastEditDate": "2022-11-26T09:02:12.000+00:00",
            "upvoteNo": 0,
            "downvoteNo": 0,
            "reports": []
        }
    ]
}
```

### CODE REVIEW

**Review by demet47 — COMMENTED** [review]
I tested the code on my local and it works fine. I also reviewed the code and no problem observed. Though you must resolve the conflicts.

**Comment by demet47** [comment]
Closes #458

**Comment by askabderon** [comment]
> I tested the code on my local and it works fine. I also reviewed the code and no problem observed. Though you must resolve the conflicts.

Done!

**Comment by CahidArda** [comment]
I am confused by this PR. It looks like it was merged but this PR is still open. Shall we close it?

**Comment by demet47** [comment]
> I am confused by this PR. It looks like it was merged but this PR is still open. Shall we close it?

Your confusion is due to neglecting the direction of the merge. The merge you see is FROM develop branch TO this branch.

**Pull request merged**
