### PR TITLE
Dev/backend/http update

### PR DESCRIPTION
**Pull request by askabderon**
Implementation of the [issue 376](https://github.com/bounswe/bounswe2022group7/issues/376)
Event and Art Item endpoints are tested:
Screen Shot 2022-11-06 at 21 13 19

### CODE REVIEW

**Comment by sabrimete** [comment]
@CahidArda Does this response satisfy your needs? If it does, I will approve the PR.

**Comment by CahidArda** [comment]
I think we should define the scope of the task better. There are currently two issues (#376 and #379) regarding the HTTP. I feel like they don't specify the task well enough. Here is the tasks we need to handle for each page:
- [ ] Signup: If the signup fails, respond with the correct header and specify what the problem is (duplicate username, duplicate email).
- [ ] Signin: If the signin fails, respond with the correct header. If signin succeds, return the token inside a JSON.
- [ ] Event and Art Item: If there is no event or art item with the provided id, respond with a 404 header and error message (What you are doing in this PR).

In this PR, I see that you are solving the third issue. I couldn't understand the response JSON though, the ss you provided shows some of the JSON response. I feel like we shouldn't have the error stack and path in the ss. Can we remove these? Also can you show us all of the JSON?

**Comment by askabderon** [comment]
@CahidArda Thanks for the detailed scope, I am agree with the specifications.
Trace is related with the application.properties e.g. not related to this code structure, I updated it as well. 
In conclusion:

- Http Response Error for Event

> {
    "timestamp": "2022-11-06T19:44:29.085+00:00",
    "status": 404,
    "error": "Not Found",
    "message": "Id is not match with any of the events in the database",
    "path": "/event/1"
}

- Http Response Error for Art Item

> {
    "timestamp": "2022-11-06T19:47:32.080+00:00",
    "status": 404,
    "error": "Not Found",
    "message": "Id is not match with any of the art items in the database",
    "path": "/art_item/0"
}
Whereas the Http Response for success scenarios are remained the same, for example;

> {
    "id": 1,
    "artItemInfo": {
        "id": 2,
        "name": "Demet is trying",
        "description": null,
        "category": null,
        "imageUrl": null,
        "labels": null
    },
    "creator": null,
    "creationDate": "2022-11-06T19:46:06.000+00:00",
    "owner": null,
    "onAuction": false,
    "auction": null,
    "lastPrice": 0.0,
    "commentList": [],
    "bookmarkedBy": []
}

**Comment by CahidArda** [comment]
The JSON content is mostly fine by me. I am only not sure about having 404 status inside the JSON but I am not confident enough on this matter to reject that without testing the response in frontend.

Which changes are you planning to complete within this PR? Will you handle the other [issues I listed above in the other endpoints](https://github.com/bounswe/bounswe2022group7/pull/378#issuecomment-1304875401)? #376 sounds generic enough to include other tasks in the scope.

**Comment by askabderon** [comment]
It also return the corresponding response, not HTTP 200 
image
Adding the error code to inside of the JSON is the default structure for failure requests. I think there is no need to explicitly remove it even if frontend does not need it.
For the other cases that you mention, I think @sabrimete is working on them on the other [PR](https://github.com/bounswe/bounswe2022group7/pull/381)

**Review by sabrimete — APPROVED** [review]
It works on my local.

**Pull request merged**
