### PR TITLE
Merge docker implementation with frontend branch

### PR DESCRIPTION
**Pull request by erimerkin**
The changes listed in issue #283 is implemented. Dockerized the frontend application resulting in production and  development images for application. 

Also CI is set up for frontend and develop branches. This CI will trigger when:
- Pull Request opens on `develop` and `frontend` branches.
- A file is changed on `./frontend` directory on `release` branch 

This PR will also act as a test for the CI.

### CODE REVIEW

**Comment by CahidArda** [comment]
I tried to build and run the docker images as you wrote in the README file. I had issues both in development and production. The problem in development seems like a problem in my local environment so it's not an issue.

In production, the tests of the frontend fail:
```
#11 1.278 > frontend@1.0.0 test
#11 1.278 > jest
#11 1.278
#11 4.712 FAIL test/Welcome.test.js
#11 4.712   ● Test suite failed to run
#11 4.712
#11 4.712     Cannot find module '../src/Welcome' from 'test/Welcome.test.js'
#11 4.712
#11 4.712       2 | import ReactDOM from 'react-dom/client'
#11 4.712       3 | import { act } from 'react-dom/test-utils'
#11 4.712     > 4 | import { Welcome } from '../src/Welcome'
#11 4.712         | ^
#11 4.712       5 |
#11 4.712       6 | describe('Welcome', () => {
#11 4.712       7 |     let container
#11 4.712
#11 4.712       at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:487:11)#11 4.712       at Object.<anonymous> (test/Welcome.test.js:4:1)
#11 4.712
#11 4.724 Test Suites: 1 failed, 1 total
#11 4.724 Tests:       0 total
#11 4.724 Snapshots:   0 total
#11 4.724 Time:        2.06 s
#11 4.724 Ran all test suites.
------
executor failed running [/bin/sh -c npm run test]: exit code: 1
```

It looks like the tests are run but they fail. I am not sure how they pass in the CI/CD of github though. Is this again an issue with my local environment? Can you run the production docker?

**Comment by erimerkin** [comment]
> I tried to build and run the docker images as you wrote in the README file. I had issues both in development and production. The problem in development seems like a problem in my local environment so it's not an issue.
> 
> In production, the tests of the frontend fail:
> 
> ```
> #11 1.278 > frontend@1.0.0 test
> #11 1.278 > jest
> #11 1.278
> #11 4.712 FAIL test/Welcome.test.js
> #11 4.712   ● Test suite failed to run
> #11 4.712
> #11 4.712     Cannot find module '../src/Welcome' from 'test/Welcome.test.js'
> #11 4.712
> #11 4.712       2 | import ReactDOM from 'react-dom/client'
> #11 4.712       3 | import { act } from 'react-dom/test-utils'
> #11 4.712     > 4 | import { Welcome } from '../src/Welcome'
> #11 4.712         | ^
> #11 4.712       5 |
> #11 4.712       6 | describe('Welcome', () => {
> #11 4.712       7 |     let container
> #11 4.712
> #11 4.712       at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:487:11)#11 4.712       at Object.<anonymous> (test/Welcome.test.js:4:1)
> #11 4.712
> #11 4.724 Test Suites: 1 failed, 1 total
> #11 4.724 Tests:       0 total
> #11 4.724 Snapshots:   0 total
> #11 4.724 Time:        2.06 s
> #11 4.724 Ran all test suites.
> ------
> executor failed running [/bin/sh -c npm run test]: exit code: 1
> ```
> 
> It looks like the tests are run but they fail. I am not sure how they pass in the CI/CD of github though. Is this again an issue with my local environment? Can you run the production docker?

@CahidArda Can you run the tests directly? The reason may be the Windows and the path as in `../src/Welcome` part.

**Comment by CahidArda** [comment]
It does run locally. It doesn't run when I attempt to run it with docker. It looks like it is supposed to work since it has passed in the GitHub actions. 

I think your implementation is correct. I will try to figure out why it doesn't run on docker on my machine. Thanks for the work and help!

**Review by CahidArda — APPROVED** [review]

**Comment by erimerkin** [comment]
> It does run locally. It doesn't run when I attempt to run it with docker. It looks like it is supposed to work since it has passed in the GitHub actions.
> 
> I think your implementation is correct. I will try to figure out why it doesn't run on docker on my machine. Thanks for the work and help!

@CahidArda I think we can remove the testing from docker implementation, I was stuck in between implementing testing in docker and before build on bare metal. Second option seems better since we can generate coverage stats from it.

**Review by CahidArda — APPROVED** [review]

**Pull request merged**
