### PR TITLE
Token based authentication

### PR DESCRIPTION
**Pull request by guneyizol**
- I changed session based authentication to token based authentication.
- We don't use flask-login anymore. Instead we are using the flask-jwt-extended library.

#### When a user signs up this way:
image
The server returns an access token.

#### Using this access token:
image
You can authorize to a jwt-protected api.

#### Login works as follows for a registered user:
image

In order to protect your api endpoint with an access token, all you need to do is:
```python
from flask_jwt_extended import jwt_required

@auth.route("/protected", methods=["GET"])  # change this route to your specific route and methods
@jwt_required()
def protected():
    return jsonify(logged_in_as=current_user.email), 200
```

As seen here, you can access the logged in user object simply using the ``current_user`` variable after doing
```python
from flask_jwt_extended import current_user
```

### CODE REVIEW

**Review by CahidArda — APPROVED** [review]
The changes look great. Also the tests and examples provided in the PR looks really useful for all the team members. Thanks for the work.

**Review by CahidArda — CHANGES_REQUESTED** [review]
One thing I realized is that I believe we no longer have a logout endpoint. Is this intentional?

Can a user logout in the current implementation?

**Comment by guneyizol** [comment]
There is no logout functionality because there are no sessions in this implementation. All authentication is done using the tokens returned by the signup or login endpoints. An http request sends the token in the Authorization header to access a token-protected endpoint. The server doesn't store session information so there cannot be a logout functionality.

**Review by CahidArda — APPROVED** [review]

**Review by CahidArda — CHANGES_REQUESTED** [review]
Sorry for the premature approve messages. I keep misusing the PR interface.

I believe there are two changes we should make:
- Can you put the `flask_jwt_extended` imports in [auth.py](https://github.com/bounswe/bounswe2022group7/pull/160/files/f7543c885bbdc88fa5c9d46b5cfe6e43875eac01#diff-80cc21754c38e1d611f30ca93c341564dcfae31551befbd0192588339fe32ac7) in a single line?
- When registering the login/signup enpoints with the `auth` blueprint, we currently don't provide a route like we do when we add the `events` blueprint. I think we should add `url_prefix="/api/"` when registering `auth` blueprint. URL routes `auth` currently uses should be reserved for the frontend.

Also I have another question. I am a bit confused about what information can be accessed through the token. In [auth.py](https://github.com/bounswe/bounswe2022group7/pull/160/files/f7543c885bbdc88fa5c9d46b5cfe6e43875eac01#diff-80cc21754c38e1d611f30ca93c341564dcfae31551befbd0192588339fe32ac7), we create the token with the `user` variable. We find the user by filtering the User table in our database by the email entered by the user. Then in the `/protected` route, we access the email of the user. Can we access other fields of the user aswell? For instance, I want to access the user id aswell. Can we access the user id with `current_user.id`?

**Review by CahidArda — APPROVED** [review]

**Comment by CahidArda** [comment]
I have completed the changes I had requested. I am adding @guneyizol as reviewer. He can approve and merge the PR.

**Comment by guneyizol** [comment]
> Also I have another question. I am a bit confused about what information can be accessed through the token. In [auth.py](https://github.com/bounswe/bounswe2022group7/pull/160/files/f7543c885bbdc88fa5c9d46b5cfe6e43875eac01#diff-80cc21754c38e1d611f30ca93c341564dcfae31551befbd0192588339fe32ac7), we create the token with the `user` variable. We find the user by filtering the User table in our database by the email entered by the user. Then in the `/protected` route, we access the email of the user. Can we access other fields of the user aswell? For instance, I want to access the user id aswell. Can we access the user id with `current_user.id`?

Yes we can access every field of a user using current_user.

**Pull request merged**
