### PR TITLE
Sign up & login functionality

### PR DESCRIPTION
**Pull request by guneyizol**
I added functionality for signing up as an artist by simpy adding an "is_artist" field to the api. Since logging in is done in the same manner for all kind of users, I haven't changed anything for the login endpoint.

image

### CODE REVIEW

**Comment by guneyizol** [comment]
I have created a frontend from for signing up. When you submit the form it redirects to the home page. I couldn't figure out how to store and use the returned token yet. I need to do some further study about it.

**Comment by guneyizol** [comment]
The template for login page is created.

**Review by CahidArda — CHANGES_REQUESTED** [review]
I am also not so sure about how we are going to use the tokens. Maybe we can discuss this in the meeting today.

I have one change request. I believe the page header of [login.html](https://github.com/bounswe/bounswe2022group7/pull/168/files#diff-1f622edfe341752666e3db0371a01d658f2059a0d7129f1cae10b871a88e0bf0) is not correct. Inside of the functionality block is still "Sign Up". It should be changed as "Log In".

**Comment by guneyizol** [comment]
> I have one change request. I believe the page header of [login.html](https://github.com/bounswe/bounswe2022group7/pull/168/files#diff-1f622edfe341752666e3db0371a01d658f2059a0d7129f1cae10b871a88e0bf0) is not correct. Inside of the functionality block is still "Sign Up". It should be changed as "Log In".

Yes, thank you. Consequences of copy pasta 😃

**Review by CahidArda — APPROVED** [review]
Thanks for the update. I believe the changes are fine.

There is one issue I noticed in our authentication system though. Passwords are passed and stored without being encrypted with an algorithm such as SHA256:
- Database holds plain passwords
- When logging in and signing up, we send the password without encrypting it.

This is something we need to fix in the future. For now I am approving these changes.

**Pull request merged**
